automation:
  - alias: Close child cover at sunset
    use_blueprint:
      path: bpaulin/close-cover-when-sun-set.yaml
      input:
        cover: cover.child

  - alias: Close office cover at sunset
    use_blueprint:
      path: bpaulin/close-cover-when-sun-set.yaml
      input:
        cover: cover.office

  - alias: Close parents_first cover at sunset
    use_blueprint:
      path: bpaulin/close-cover-when-sun-set.yaml
      input:
        cover: cover.parents_first

  - alias: Close parents_second cover at sunset
    use_blueprint:
      path: bpaulin/close-cover-when-sun-set.yaml
      input:
        cover: cover.parents_second
