---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: flix
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "jackett.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: Prefix
        tls:
          - hosts:
              - "jackett.${SECRET_DOMAIN}"
            secretName: "jackett-tls"
