---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: flix
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    image:
      tag: "v0.20.314"
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "external"
          # traefik.ingress.kubernetes.io/router.middlewares: networking-protected@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "jackett.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        mountPath: /config
