cover:
  - platform: cover_rf_time_based
    devices:
      office:
        name: office
        travelling_time_up: 26
        travelling_time_down: 24
        close_script_entity_id: script.office_cover_down
        stop_script_entity_id: script.office_cover_stop
        open_script_entity_id: script.office_cover_up

script:
  office_cover_down:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.office_cover_known_action
      - service: cover.close_cover
        data:
          entity_id: cover.a0pl6
      - wait_for_trigger:
          - platform: state
            entity_id: cover.a0pl6
      - service: automation.turn_on
        data:
          entity_id: automation.office_cover_known_action

  office_cover_stop:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.office_cover_known_action
      - service: cover.stop_cover
        data:
          entity_id: cover.a0pl6
      - wait_for_trigger:
          - platform: state
            entity_id: cover.a0pl6
      - service: automation.turn_on
        data:
          entity_id: automation.office_cover_known_action

  office_cover_up:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.office_cover_known_action
      - service: cover.open_cover
        data:
          entity_id: cover.a0pl6
      - wait_for_trigger:
          - platform: state
            entity_id: cover.a0pl6
      - service: automation.turn_on
        data:
          entity_id: automation.office_cover_known_action

automation office_cover:
  - alias: office_cover_known_action
    trigger:
      platform: state
      entity_id: cover.a0pl6
    action:
      service: cover_rf_time_based.set_known_action
      data:
        entity_id: cover.office
        action: >-
          {% if trigger.to_state.state == 'opening' %}
            open
          {% elif trigger.to_state.state == 'closing' %}
            close
          {% else %}
            stop
          {% endif %}

homeassistant:
  customize:
    cover.office:
      friendly_name: "Bureau"

cloud:
  google_actions:
    filter:
      include_entities:
        - cover.office
    entity_config:
      cover.office:
        aliases:
          - volet
          - store
        room: Bureau

recorder:
  include:
    entities:
      - cover.office
