cover:
  - platform: cover_rf_time_based
    devices:
      living_small:
        name: living_small
        travelling_time_up: 26
        travelling_time_down: 24
        close_script_entity_id: script.living_small_cover_down
        stop_script_entity_id: script.living_small_cover_stop
        open_script_entity_id: script.living_small_cover_up

script:
  living_small_cover_down:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.living_small_cover_known_action
      - service: cover.close_cover
        data:
          entity_id: cover.a1pl3
      - wait_for_trigger:
          - platform: state
            entity_id: cover.a1pl3
      - service: automation.turn_on
        data:
          entity_id: automation.living_small_cover_known_action

  living_small_cover_stop:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.living_small_cover_known_action
      - service: cover.stop_cover
        data:
          entity_id: cover.a1pl3
      - wait_for_trigger:
          - platform: state
            entity_id: cover.a1pl3
      - service: automation.turn_on
        data:
          entity_id: automation.living_small_cover_known_action

  living_small_cover_up:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.living_small_cover_known_action
      - service: cover.open_cover
        data:
          entity_id: cover.a1pl3
      - wait_for_trigger:
          - platform: state
            entity_id: cover.a1pl3
      - service: automation.turn_on
        data:
          entity_id: automation.living_small_cover_known_action

automation living_small_cover:
  - alias: living_small_cover_known_action
    trigger:
      platform: state
      entity_id: cover.a1pl3
    action:
      service: cover_rf_time_based.set_known_action
      data:
        entity_id: cover.living_small
        action: >-
          {% if trigger.to_state.state == 'opening' %}
            open
          {% elif trigger.to_state.state == 'closing' %}
            close
          {% else %}
            stop
          {% endif %}

homeassistant:
  customize:
    cover.living_small:
      friendly_name: "Salon (petit)"

cloud:
  google_actions:
    filter:
      include_entities:
        - cover.living_small
    entity_config:
      cover.living_small:
        name: Petit
        aliases:
          - petit volet
          - petit store
        room: Salon
