cover:
  - platform: cover_rf_time_based
    devices:
      parents_second:
        name: parents_second
        travelling_time_up: 26
        travelling_time_down: 24
        close_script_entity_id: script.parents_second_cover_down
        stop_script_entity_id: script.parents_second_cover_stop
        open_script_entity_id: script.parents_second_cover_up

script:
  parents_second_cover_down:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.parents_second_cover_known_action
      - service: cover.close_cover
        data:
          entity_id: cover.a1pl6
      - wait_for_trigger:
        - platform: state
          entity_id: cover.a1pl6
      - service: automation.turn_on
        data:
          entity_id: automation.parents_second_cover_known_action

  parents_second_cover_stop:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.parents_second_cover_known_action
      - service: cover.stop_cover
        data:
          entity_id: cover.a1pl6
      - wait_for_trigger:
        - platform: state
          entity_id: cover.a1pl6
      - service: automation.turn_on
        data:
          entity_id: automation.parents_second_cover_known_action

  parents_second_cover_up:
    sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.parents_second_cover_known_action
      - service: cover.open_cover
        data:
          entity_id: cover.a1pl6
      - wait_for_trigger:
        - platform: state
          entity_id: cover.a1pl6
      - service: automation.turn_on
        data:
          entity_id: automation.parents_second_cover_known_action

automation parents_second_cover:
  - alias: parents_second_cover_known_action
    trigger:
      platform: state
      entity_id: cover.a1pl6
    action:
      service: cover_rf_time_based.set_known_action
      data:
        entity_id: cover.parents_second
        action: >-
          {% if trigger.to_state.state == 'opening' %}
            open
          {% elif trigger.to_state.state == 'closing' %}
            close
          {% else %}
            stop
          {% endif %}

homeassistant:
  customize:
    cover.parents_second:
      friendly_name: 'Parents (placard)'

cloud:
  google_actions:
    filter:
      include_entities:
        - cover.parents_second
    entity_config:
      cover.parents_second:
        aliases:
          - volet du placard
          - store du placard
          - volet de bruno
          - store de bruno
        room: Chambre
