# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.19.0
    hooks:
      - id: yamllint

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v1.0.0
    hooks:
      - id: docker-compose-check
