---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1sjwjnh59cnt7xjtuxfjxrd2ln558s35tzw7j5kkw5284f86yv5xqrcz2n9
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1sjwjnh59cnt7xjtuxfjxrd2ln558s35tzw7j5kkw5284f86yv5xqrcz2n9
