---

version: "3.3"
services:
  duckdns:
    image: linuxserver/duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DOMAIN_NAMES}
      - TOKEN=${DOMAIN_TOKEN}
      - LOG_FILE=false
    restart: unless-stopped

  traefik:
    image: traefik:v2.2
    ports:
      - "10443:443"
      - "8080:8080"  # internal dashboard
    environment:
      TRAEFIK_ENTRYPOINTS_WEBSECURE: "true"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
      TRAEFIK_API: "true"
      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_API_INSECURE: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${ACME_EMAIL}
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE: "/letsencrypt/acme.json"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_TLSCHALLENGE: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_DNSCHALLENGE_PROVIDER: "duckdns"
      DUCKDNS_TOKEN: ${DOMAIN_TOKEN}
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_PROVIDERS_FILE_DIRECTORY: "/etc/traefik/dynamic/"
    volumes:
      - ${ROOT_DATA}/letsencrypt:/letsencrypt
      - ${ROOT_DATA}/traefik:/etc/traefik
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.secured.chain.middlewares: "auth-users, test-ratelimit"
      traefik.http.middlewares.auth-users.basicauth.users: "${BASIC_AUTH}"
      traefik.http.middlewares.known-ips.ipwhitelist.sourceRange: "${WHITELIST_RANGE}"
      traefik.http.middlewares.test-ratelimit.ratelimit.average: "100"
      traefik.http.middlewares.test-ratelimit.ratelimit.burst: "100"
      traefik.http.routers.hass.rule: "Host(`${HOME_DOMAIN}`)"
      traefik.http.routers.hass.service: "hass@file"
      traefik.http.routers.hass.entrypoints: "websecure"
      traefik.http.routers.hass.tls: "true"
      traefik.http.routers.hass.tls.certresolver: "letsencrypt"
      traefik.http.routers.hass.tls.domains[0].main: "${HOME_DOMAIN}"
      traefik.http.routers.hass.tls.domains[0].sans: "*.${HOME_DOMAIN}"
    restart: unless-stopped
