light:
  - platform: group
    name: bulbs_corridor_ceiling
    entities:
      - light.bulb_corridor_ceiling_1
      - light.bulb_corridor_ceiling_2
      - light.bulb_corridor_ceiling_3

  - platform: template
    lights:
      corridor_ceiling:
        level_template: "{% if states('light.bulbs_corridor_ceiling')=='on' %}{{ state_attr('light.bulbs_corridor_ceiling', 'brightness') }}{% else %}0{% endif %}"
        value_template: "{{ states('light.a1pl1')=='on' and states('light.bulbs_corridor_ceiling')=='on' }}"
        turn_on:
          service: light.turn_on
          data_template:
            entity_id:
              - light.bulbs_corridor_ceiling
              - light.a1pl1
        turn_off:
          service: light.turn_off
          data_template:
            entity_id: light.bulbs_corridor_ceiling
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.bulbs_corridor_ceiling
            brightness: "{{ brightness }}"

homeassistant:
  customize:
    light.corridor_ceiling:
      friendly_name: 'Couloir'
      icon: mdi:ceiling-light

cloud:
  google_actions:
    filter:
      include_entities:
        - light.corridor_ceiling
    entity_config:
      light.corridor_ceiling:
        aliases: []
        room: Couloir

