light:
  - platform: group
    name: bulbs_living_ceiling
    entities:
      - light.bulb_living_ceiling_1
      - light.bulb_living_ceiling_2
      - light.bulb_living_ceiling_3
      - light.bulb_living_ceiling_4
      - light.bulb_living_ceiling_5

  - platform: template
    lights:
      living_ceiling:
        level_template: "{{ state_attr('light.bulbs_living_ceiling', 'brightness') }}"
        value_template: "{{ states('light.a0pl2') }}"
        turn_on:
          service: light.turn_on
          data_template:
            entity_id: light.a0pl2
        turn_off:
          service: light.turn_off
          data_template:
            entity_id: light.a0pl2
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.bulbs_living_ceiling
            brightness: "{{ brightness }}"

homeassistant:
  customize:
    light.living_ceiling:
      friendly_name: 'Salon (plafond)'
      icon: mdi:ceiling-light

cloud:
  google_actions:
    filter:
      include_entities:
        - light.living_ceiling
    entity_config:
      light.living_ceiling:
        name: Plafond
        aliases:
          - grande lumière
        room: Salon

