light:
  - platform: template
    lights:
      living_plug:
        level_template: "{{ state_attr('light.bulb_living_plug', 'brightness') }}"
        value_template: "{{ states('light.a0pl1') }}"
        temperature_template: "{{ state_attr('light.bulb_living_plug', 'color_temp') }}"
        turn_on:
          service: light.turn_on
          data_template:
            entity_id: light.a0pl1
        turn_off:
          service: light.turn_off
          data_template:
            entity_id: light.a0pl1
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.bulb_living_plug
            brightness: "{{ brightness }}"
        set_temperature:
          service: light.turn_on
          data_template:
            entity_id: light.bulb_living_plug
            color_temp: "{{ color_temp }}"

homeassistant:
  customize:
    light.living_plug:
      friendly_name: 'Salon (prise)'
      icon: mdi:floor-lamp

cloud:
  google_actions:
    filter:
      include_entities:
        - light.living_plug
    entity_config:
      light.living_plug:
        name: Prise
        aliases:
          - lampadaire
          - petite lumière
        room: Salon

