light:
  - platform: group
    name: parents_mum
    entities:
      - light.bulb_parents_mum

homeassistant:
  customize:
    light.bulb_parents_mum:
      friendly_name: 'Emma'
      icon: mdi:lamp

cloud:
  google_actions:
    filter:
      include_entities:
        - light.bulb_parents_mum
    entity_config:
      light.bulb_parents_mum:
        aliases:
          - Chevet d'Emma
        room: Chambre
