---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: forecastle-crd-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/stakater/Forecastle.git
  ref:
    tag: v1.0.78
  ignore: |
    # exclude all
    /*
    # path to crds
    !/deployments/kubernetes/chart/forecastle/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forecastle-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: forecastle-crd-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: forecastleapps.forecastle.stakater.com
