app_jellyfin:
  name: jellyfin

  namespace: sh-flix

  helm_repo:
    - name: k8s-at-home
      repo_url: https://k8s-at-home.com/charts/

  charts:
    - ref: "k8s-at-home/jellyfin"
      chart_values:
        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - host: "jellyfin.sillykube"
                paths:
                  - path: "/"
                    pathType: Prefix
        persistence:
          config:
            enabled: true
            type: hostPath
            mountPath: /config
            hostPath: "/home/kah/config/jackett"

          medias:
            enabled: true
            type: hostPath
            mountPath: /medias
            hostPath: "/home/kah/medias"
