app_jellyfin:
  name: jellyfin

  folders:
    - medias/tv
    - medias/movies
    - config/jellyfin

  portal:
    - name: Jellyfin
      subtitle: "Lecteur"
      url: "https://jellyfin.{{ cloudflare_domain }}"
      logo: https://avatars.githubusercontent.com/u/45698031?s=200&v=4
      target: "_blank"
      group: video
      public: false

  namespace: sh-flix

  helm_repo:
    - name: k8s-at-home
      repo_url: https://k8s-at-home.com/charts/

  charts:
    - ref: "k8s-at-home/jellyfin"
      chart_values:
        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            hosts:
              - host: "jellyfin.{{ cloudflare_domain }}"
                paths:
                  - path: "/"
                    pathType: Prefix
        persistence:
          config:
            enabled: true
            type: hostPath
            mountPath: /config
            hostPath: "/home/kah/config/jackett"

          medias:
            enabled: true
            type: hostPath
            mountPath: /medias
            hostPath: "/home/kah/medias"
