app_jellyfin:
  name: jellyfin
  state: present

  folders:
    - medias/tv
    - medias/movies
    - config/jellyfin

  portal:
    - name: Jellyfin
      subtitle: "Lecteur"
      url: "https://jellyfin.{{ cloudflare_domain }}"
      logo: https://github.com/NX211/homer-icons/raw/master/png/jellyfin.png
      target: "_blank"
      group: video
      public: false

  namespace: sh-flix

  helm_repo:
    - name: k8s-at-home
      repo_url: https://k8s-at-home.com/charts/

  charts:
    - ref: "k8s-at-home/jellyfin"
      chart_values:
        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            hosts:
              - host: "jellyfin.{{ cloudflare_domain }}"
                paths:
                  - path: "/"
                    pathType: Prefix
          external:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: external
              external-dns.alpha.kubernetes.io/target: "{{ cloudflare_backend }}"
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.middlewares: sh-core-forward-auth@kubernetescrd,sh-core-cloudflare-api-whitelist@kubernetescrd
            hosts:
              - host: "jellyfin.{{ cloudflare_domain }}"
                paths:
                  - path: "/"
                    pathType: Prefix
        persistence:
          config:
            enabled: true
            type: hostPath
            mountPath: /config
            hostPath: "{{ sh_apps_path_base }}/config/jellyfin"

          medias:
            enabled: true
            type: hostPath
            mountPath: /medias
            hostPath: "{{ sh_apps_path_base }}/medias"
