---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    nfs_exports:
      - "/data *(rw,sync,no_root_squash)"
  tasks:
    - file:
        path: /data/hdd
        state: directory

    - name: Mount up device by UUID
      ansible.posix.mount:
        path: /data/hdd
        src: UUID=875437fe-0d67-4323-b820-575ad4adeb37
        fstype: ext4
        state: mounted

    - import_role:
        name: geerlingguy.nfs
