apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medias
  namespace: flix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
