app_hass:
  name: hass
  state: present

  namespace: sh-home

  helm_repo:
    - name: k8s-at-home
      repo_url: https://k8s-at-home.com/charts/

  charts:
    - ref: "k8s-at-home/home-assistant"
      chart_values: {}
