app_esphome:
  name: esphome
  state: present

  namespace: sh-home

  helm_repo:
    - name: k8s-at-home
      repo_url: https://k8s-at-home.com/charts/

  charts:
    - ref: "k8s-at-home/esphome"
      chart_values: {}
