# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/LTD3joHqkeEiTZk,iv:zFmbWjbj1JjfTl7MZAJbOMPTWlTsWy/fGKNwFlhSKXQ=,tag:PojKplEaD/15FqttpnJTyg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PPsLI4zXGgXw35c5dI453tKW6n7kmjI=,iv:MAhhRglY7aN+vOLVQrNKV5lg6gX1A5svQfx7O314Mu4=,tag:UoYCvZ9Ir3alcFKZ6VDRzw==,type:str]
    SECRET_CLOUDFLARE_KEY: ENC[AES256_GCM,data:QQeAD2hTjeh5sqfwfFmbJQNMSwMSCkdiFQB9+57YsY+MKRNhFQ==,iv:L/WqdzsfM3CpVx5lY0LVIuuZjndUuooWluZ9rHA2ua8=,tag:CKHQvovfL19uW7eQDf7CxQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:sKk2HLLYt0l8,iv:XHR93eWmqWgSHIWQtlJfcYmgnXTrSkqVw9xbutsGc/I=,tag:c8/brBegWI4I5k1sa4zTlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjwjnh59cnt7xjtuxfjxrd2ln558s35tzw7j5kkw5284f86yv5xqrcz2n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVAzVjlhNWpyUFFPT1cz
            dFhJU0tKcDlSQlAxL2JmaHZnOXNCRGE0UUNNClFpbWhObjJHZkJwckg5ZTFzV1FG
            ZzErQVdYS2YyaU5sU3R3TGJpMHVXcGcKLS0tIGtLRjdwSUFYeitjUDAyTGJaL1FG
            Q0E2VDFQYk1PbURKUWtHMUo5ejFMTU0KnHT1djZ8etySMg2HnEJSR0DqFgPcRX+g
            1QO6hn5ymONw9T24lzF2Zaihbv86+oOcAsOpBFCnZqjbbqdtMgWJWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-05T17:20:12Z"
    mac: ENC[AES256_GCM,data:KjlTI0aYbCXtNgT0SRt9OKKBTdGXVIVxjEcs7JTYXtyhvybSlkKjRj7+xlmFk0kQvk/zU9PbPm+sN548HOXOk0UGYys4tDjIYKWMjBYvucB7eTbdFpHGvuC3sTv5vPIkF19J8QQMzvnS3opeNUOyRHkO82JUDzxVVnBv3Qsmpb0=,iv:kbXyYEt4oOJhqeMcphuF68dP9T/ucobj7dpOFH0H8AA=,tag:JFP1X3C75W9d9C/OK7562w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
