title: Sillyhome
subtitle: Public
services:
- items:
    - name: "Github repository"
      subtitle: "Everything here is as-code"
      url: "https://github.com/bpaulin/sillyhome"
      target: "_blank"

    - name: "Documentation"
      subtitle: "Well, at least this page exists"
      url: "https://bpaulin.net/sillyhome"
      target: "_blank"

    - name: "Private apps"
      subtitle: "If you're sitting on my sofa..."
      url: "http://sillykube"
      target: "_blank"
