---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: flix
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "external"
          traefik.ingress.kubernetes.io/router.middlewares: networking-protected@kubernetescrd
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        mountPath: /config
