apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - service-monitor.yaml
configMapGenerator:
  - name: longhorn-grafana-dashboards
    files:
      - dashboards/longhorn-example-v1-1-0_rev6.json
    options:
      labels:
        grafana_dashboard: "1"
