---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari-private
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      instanceName: private
      defaultEnable: false
      namespaceSelector:
        any: true
      name: "silly me"
      customApps: []
      groups: []
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "external"
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: networking-protected@kubernetescrd
        hosts:
          - host: "private.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: true
        existingClaim: hajimari-private-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-private-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
