---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: error-pages
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TEMPLATE_NAME: ghost
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "external"
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "error-pages.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: Prefix
