# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:EIl1B+0TIkUzC0c1NaO0uD+Specx5ogjuRxEjrSBXcxucBuFFA==,iv:dArznj1SoVw6ic4QTeeCFbqaLtc66/tcTLFmHMUcPW8=,tag:kvNC5iKvpfb5I+CgTlj5/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjwjnh59cnt7xjtuxfjxrd2ln558s35tzw7j5kkw5284f86yv5xqrcz2n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MFNCZ2J1Q0U0dWZWRlN0
            U0ltYmREN0sxcGw3NlJkbnFzVUhPbGR2Y1gwCmtiM2tQSys5SlF4czRCWWNnVlhz
            YzA3Y1YrbDVWVkdGRURtejVhN1Q5YzgKLS0tIDF1TGpUZE1lRlFiYzhmS2MrUHFz
            d3NDS1hScGlPZWplZTJrbTVPNEo0c0EKU7Vyd6XjaNbEp0r7CQD7y92eW4M+2mSo
            Kv/RuTfPihU17u/CXNzPbMTDGNbAFq3f61JaWJEooGovDCs6dqEe4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-03T11:49:05Z"
    mac: ENC[AES256_GCM,data:NuzEhSYtaNAnVu65bzOY8PesXSGzZ/AbSFztCrN7VBlxk+M4OYxKxBVAGSU6jQb0zWCfhCtRRkubxhuieY6Fme9OiPCvAn4K0viqgMw88LCIeiBMTNYs+72PPf6kw8Kw59UkbG3Huv4dGXSWyrwn1uQvX18xOn0ROcqPPLFKPXE=,iv:BXzbBYf0PK8mazbDWHIVOsDq+TQVuMhJDtcxuVR/sFI=,tag:H+k96vfFGwA1tbGJDjgBoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
