app_traefik:
  portal:
    - name: "Routeur"
      subtitle: "Traefik"
      icon: "fas fa-route"
      url: "http://traefik.sillykube/dashboard/"
      target: "_blank"
      group: core
      public: false

  name: traefik

  namespace: sh-core

  manifests:
    - name: traefik-dashboard
      manifest:
        apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRoute
        spec:
          entryPoints:
            - web
          routes:
            - kind: Rule
              match: Host(`traefik.sillykube`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
              services:
                - kind: TraefikService
                  name: api@internal
