app_traefik:
  portal:
    - name: "Routeur"
      subtitle: "Traefik"
      icon: "fas fa-route"
      url: "https://traefik.{{ cloudflare_domain }}/dashboard/"
      target: "_blank"
      group: core
      public: false

  name: traefik

  namespace: sh-core

  manifests:
    - name: traefik
      namespace: kube-system
      manifest:
        apiVersion: helm.cattle.io/v1
        kind: HelmChartConfig
        spec:
          valuesContent: |-
            globalArguments:
              - --entryPoints.websecure.forwardedHeaders.trustedIPs={{ cloudflare_ips | join(',') }}
              - --entryPoints.external.forwardedHeaders.trustedIPs={{ cloudflare_ips | join(',') }}
              - --certificatesresolvers.myresolver.acme.email={{ cloudflare_api_email }}
              - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
              - --certificatesresolvers.myresolver.acme.storage=/data/acme.json
            env:
              - name: CF_API_EMAIL
                value: {{ cloudflare_api_email }}
              - name: CF_API_KEY
                value: {{ cloudflare_api_key }}
            hostNetwork: true
            ports:
              external:
                port: 8444
                expose: true
                exposedPort: 444
                protocol: TCP
                tls:
                  enabled: true
            persistence:
              enabled: true
              name: data
              accessMode: ReadWriteOnce
              size: 128Mi
              path: /data

    - name: traefik-dashboard
      manifest:
        apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRoute
        spec:
          entryPoints:
            - websecure
          routes:
            - kind: Rule
              match: "Host(`traefik.{{ cloudflare_domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
              services:
                - kind: TraefikService
                  name: api@internal

    - name: cloudflare-api-whitelist
      manifest:
        apiVersion: traefik.containo.us/v1alpha1
        kind: Middleware
        spec:
          ipWhiteList:
            sourceRange: "{{ cloudflare_ips }}"

    - name: basic-auth
      manifest:
        apiVersion: traefik.containo.us/v1alpha1
        kind: Middleware
        spec:
          basicAuth:
            secret: authsecret

    - name: authsecret
      manifest:
        apiVersion: v1
        kind: Secret
        data:
          users: |2
            YnJ1bm86JGFwcjEkSGs4NWJNNG8kWnVEdnVjN1dKeUZ5cjFtbnRTeGtQMQoK
