---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: flix
spec:
  interval: 5m
  chart:
    spec:
      chart: transmission
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "transmission.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: Prefix
        tls:
          - hosts:
              - "transmission.${SECRET_DOMAIN}"
            secretName: "transmission-tls"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        mountPath: /config
