# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    cloudflare_api_key: ENC[AES256_GCM,data:+ad/9pvGLSAzWffOZCgGoPKnoozoxYyyROUsF+ldNk02nxvKpA==,iv:4siZzAqhVMnkgDmonZ50nPY9LIfhiGDjkXpNrPxZ+aw=,tag:dbpID3mfJGo7z5c/wC9DuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjwjnh59cnt7xjtuxfjxrd2ln558s35tzw7j5kkw5284f86yv5xqrcz2n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVXJ4aEdDckJoWjV6c2Zk
            enVBRXZyNzBFQzhvTy92N0UzN0NGaHJuSFdBCk1BdzUrWXNNYjdYK2NSb1krQ0RK
            dkdIenFmY0JBTnBFZ1NIUjJtVm56WDAKLS0tIHVhMjJJRGxyOXNwM1hNbjZkYjFG
            YnVKTmNuWVdacCtqNVJsQmNYUFJpQWMKRuJ1kHzuRE3ayE2qiYU6+q3Nwe4EV3Th
            25yziF+KjpspnosuY2x2kyRcZCONqwkolhZ5q3ivxlMF6kYWErOBcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-03T20:03:22Z"
    mac: ENC[AES256_GCM,data:oTvEPfo4GPgenK7FN8jiKoCn5S/Czn8n8VvirxuGGzNBmO6FUBhzwGjVCcP773AIb3bLFDkWIwMvmXH3+g9t9hgvSAlcbIjy7CXRbX/4LRn5dXHnYz1v6O3ZcOIjfQLRF/Lq+JB7uCP4ovij+f1C0qaiUtB3yy8V25nZS2/DeIk=,iv:j1sy/hCMC1PcXPkaVUvDcsu/QgLMrQ6cGqYbb07OFEo=,tag:z7RtzudWS0G5U2Y1+oL6Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
