sensor:
  - platform: template
    sensors:
      battery_climate_child:
        unit_of_measurement: '%'
        device_class: 'battery'
        value_template: "{{ state_attr('climate.netatmo_chambre_de_lise', 'battery_level') }}"

homeassistant:
  customize:
    climate.netatmo_chambre_de_lise:
      friendly_name: "Chambre de Lise"

cloud:
  google_actions:
    filter:
      include_entities:
        - climate.netatmo_chambre_de_lise
    entity_config:
      climate.netatmo_chambre_de_lise:
        room: Chambre de Lise

recorder:
  include:
    entities:
      - climate.netatmo_chambre_de_lise
