sensor:
  - platform: template
    sensors:
      battery_climate_living:
        unit_of_measurement: "%"
        device_class: "battery"
        value_template: "{{ state_attr('climate.netatmo_salon', 'battery_level') }}"

homeassistant:
  customize:
    climate.netatmo_salon:
      friendly_name: "Salon"

cloud:
  google_actions:
    filter:
      include_entities:
        - climate.netatmo_salon
    entity_config:
      climate.netatmo_salon:
        room: Salon

recorder:
  include:
    entities:
      - climate.netatmo_salon
